### ISSUE TITLE
info

### ISSUE THREAD

**Issue by saqie1393** [baselsayeh/e5577s_modified_source#1]
how to complied in already install frimware....how to any step instruction?

**Comment by baselsayeh** [comment]
@saqie1393 
I made a new repo for the kernel modifications
[https://github.com/baselsayeh/e5577s_321_kernel](https://github.com/baselsayeh/e5577s_321_kernel)
The compiled kernel itself works (possibly with bugs/crashes), But
Take note that download mode does not work (You will possibly be stuck on the buggy compiled kernel, and cannot go back to the original one, without the pin shorting method).
